### ISSUE TITLE
Parse and display results of learningTaskAndExamList

### ISSUE THREAD

**Issue by hey2022** [hey2022/tls-xb#42]
**Describe the solution you'd like**
Parse and display the results of learningTaskAndExamList from GetDynamicScoreDetail.
The tasks should be a list under the evaluation project.

**Describe alternatives you've considered**
This method should be faster than fetching all tasks (no DDoSing) and should be easier to implement.

**Additional context**
It seems like this feature was recently added to xiaobao.

**Comment by wusitee** [comment]
Yes, but how can we display it
