### ISSUE TITLE
Another way to display captcha

### ISSUE THREAD

**Issue by lanbinleo** [hey2022/tls-xb#52]
**Is your feature request related to a problem? Please describe.**
Yes, because now captcha is displaying on the terminal using some cargo libs. However, there may be some building problem and other potential threat using these libraries while cross-platform. 

**Describe the solution you'd like**
Instead, we can download (or write) the captcha into a image file, and automatically open it using user's picture browsing, and let the user view it and type the captcha.

**Describe alternatives you've considered**
It is also viable through cross-platform UI libraries to display captcha, however, it may become too complicated to a CLI tool.

**Comment by hey2022** [comment]
The current library being used is [viuer](https://docs.rs/viuer/latest/viuer/) where "[Kitty](https://sw.kovidgoyal.net/kitty/graphics-protocol.html) and [iTerm](https://iterm2.com/documentation-images.html) graphic protocols are supported and used by default, if detected. If not, viuer will fall back to using regular half blocks instead (▄ and ▀)."

Sixel support is behind a feature flag as it may cause problems with building on Windows or macOS  #46, however it is not required for displaying the captcha as half blocks are sufficient for this. Half blocks should be supported by any terminal with Unicode support.

**Comment by hey2022** [comment]
Example of half blocks:
![image](https://github.com/user-attachments/assets/823c180a-2365-4a77-ac08-ce6f4417b068)
