### ISSUE TITLE
Add Version Check Feature After Score Calculation

### ISSUE THREAD

**Issue by lanbinleo** [hey2022/tls-xb#59]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I don't know if there is a new version of the software available. This can lead to missing out on important updates and improvements.

**Describe the solution you'd like**
I would like the software to check for the latest version after each score calculation. Specifically, it should request a file from GitHub that contains the version number. If the latest version number is greater than the local version number, the software should notify the user that a new version is available. In the future, we might add a one-click upgrade feature. Given that more students are using this program, we should start making it more user-friendly.

**Describe alternatives you've considered** 
An alternative solution could be to manually check for updates on the GitHub repository, but this is less convenient and can be easily overlooked by users.

**Comment by hey2022** [comment]
Can probably be done with [cargo dist](https://opensource.axo.dev/cargo-dist/book/installers/updater.html).

**Comment by wusitee** [comment]
So, what's going on?

**Comment by lanbinleo** [comment]
:(

**Comment by hey2022** [comment]
I think it is out of scope of the program to manage its version. That is the responsibility of the package manager.
